apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: repo-rover-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/burner-lalsinna/repo-rover/repo-rover:latest
          env:
          ports:
            - containerPort: 4000